appName: order-api
appType: app
cluster: kind-prod
envName: prod
rollout:
  image:
    repository: ghcr.io/jfillman/order-api
    tag: 0.1.2-13f78ae
  ports:
    - name: http
      containerPort: 8080
releaseTracking:
  relayUrl: http://10.89.0.2:30880/outcome/kind-prod
  cluster: kind-prod
  appNamespace: app-order-api-cicd
  gitUrl: https://github.com/jfillman/order-api
  gitRevision: 13f78ae9af937eb616fc84de54df5a1ae385d942
  flowStartTime: "2026-08-25T08:44:32.053540983Z"
  chainId: db873c1f-44db-4b23-8278-8881c15cf484
  prUrl: https://github.com/jfillman/gitops-order-api/pull/2
  prCreatedAt: "2026-08-25T08:56:20.530335943Z"
  configJsonB64: ewogICJhcGlWZXJzaW9uIjogInBsYXRmb3JtL3YxIiwKICAia2luZCI6ICJQaXBlbGluZUNvbmZpZyIsCiAgImJ1aWxkIjogewogICAgImFnZW50IjogIm9wZW5qZGstMjEiLAogICAgImRvY2tlcmZpbGUiOiAiLi9Eb2NrZXJmaWxlIiwKICAgICJ1bml0VGVzdCI6IHsKICAgICAgImVuYWJsZWQiOiBmYWxzZQogICAgfQogIH0sCiAgImVwaGVtZXJhbEVudmlyb25tZW50cyI6IHsKICAgICJwdWxsUmVxdWVzdCI6IHsKICAgICAgImVuYWJsZWQiOiB0cnVlCiAgICB9LAogICAgInR0bCI6ICI1ZCIKICB9LAogICJnb3Zlcm5hbmNlIjogewogICAgInNhc3QiOiBmYWxzZSwKICAgICJpbWFnZVNjYW4iOiBmYWxzZSwKICAgICJwb2xpY3lDaGVjayI6IGZhbHNlLAogICAgInNib20iOiBmYWxzZSwKICAgICJhbGxvd2VkQ29tbWl0U2lnbmVycyI6IFsKICAgICAgImNyb3NzZmFkZXJAZ21haWwuY29tIiwKICAgICAgIjcyNjgzMzcramZpbGxtYW5AdXNlcnMubm9yZXBseS5naXRodWIuY29tIgogICAgXQogIH0sCiAgInNlY3JldHMiOiBbCiAgICB7CiAgICAgICJuYW1lIjogInNsYWNrLXdlYmhvb2stdXJsIgogICAgfQogIF0sCiAgIm5vdGlmaWNhdGlvbnMiOiB7CiAgICAic2xhY2siOiB7CiAgICAgICJlbmFibGVkIjogdHJ1ZSwKICAgICAgImNoYW5uZWwiOiAiI2FsbC1pZHAtbGFiIgogICAgfQogIH0sCiAgImRlcGxveSI6IHsKICAgICJsb3dlckVudmlyb25tZW50cyI6IFsKICAgICAgImRldiIKICAgIF0sCiAgICAidXBwZXJFbnZpcm9ubWVudHMiOiBbCiAgICAgIHsKICAgICAgICAibmFtZSI6ICJwcm9kIiwKICAgICAgICAiY2x1c3RlciI6ICJraW5kLXByb2QiCiAgICAgIH0KICAgIF0KICB9LAogICJwaXBlbGluZXMiOiB7CiAgICAiY2kiOiB7CiAgICAgICJ0cmlnZ2VyIjogewogICAgICAgICJzb3VyY2UiOiAiZ2l0IiwKICAgICAgICAiZXZlbnQiOiAicHVzaCIsCiAgICAgICAgImJyYW5jaCI6ICJtYWluIgogICAgICB9LAogICAgICAic3RlcHMiOiBbCiAgICAgICAgewogICAgICAgICAgInN0YWdlIjogImJ1aWxkIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgInN0YWdlIjogImRlcGxveSIsCiAgICAgICAgICAiZW52IjogImRldiIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJzdGFnZSI6ICJyZWxlYXNlIiwKICAgICAgICAgICJlbnYiOiAicHJvZCIKICAgICAgICB9CiAgICAgIF0KICAgIH0KICB9Cn0K
