appName: order-api
appType: app
cluster: kind-prod
envName: prod
rollout:
  image:
    repository: ghcr.io/jfillman/order-api
    tag: 0.1.0-59c7b8f
  ports:
    - name: http
      containerPort: 8080
releaseTracking:
  relayUrl: http://dev.kiac.local:30880/outcome/kind-prod
  cluster: kind-prod
  appNamespace: app-order-api-cicd
  gitUrl: https://github.com/jfillman/order-api
  gitRevision: 59c7b8fc7ff06501714ad31bf71d3398dadb2e69
  flowStartTime: "2026-09-04T20:57:55.430371011Z"
  chainId: 20b4a57e-865d-4a66-a2d0-127e11f21ab4
  prUrl: https://github.com/jfillman/gitops-order-api/pull/15
  prCreatedAt: "2026-08-30T08:50:19.904229448Z"
  configJsonB64: ewogICJhcGlWZXJzaW9uIjogInBsYXRmb3JtL3YxIiwKICAia2luZCI6ICJQaXBlbGluZUNvbmZpZyIsCiAgImJ1aWxkIjogewogICAgImFnZW50IjogIm9wZW5qZGstMjEiLAogICAgImRvY2tlcmZpbGUiOiAiLi9Eb2NrZXJmaWxlIiwKICAgICJ1bml0VGVzdCI6IHsKICAgICAgImVuYWJsZWQiOiBmYWxzZQogICAgfSwKICAgICJjYWNoZSI6IHsKICAgICAgImVuYWJsZWQiOiB0cnVlLAogICAgICAic2l6ZSI6ICJzbWFsbCIKICAgIH0KICB9LAogICJlcGhlbWVyYWxFbnZpcm9ubWVudHMiOiB7CiAgICAicHVsbFJlcXVlc3QiOiB7CiAgICAgICJlbmFibGVkIjogdHJ1ZQogICAgfSwKICAgICJ0dGwiOiAiNWQiCiAgfSwKICAiZ292ZXJuYW5jZSI6IHsKICAgICJzYXN0IjogZmFsc2UsCiAgICAiaW1hZ2VTY2FuIjogZmFsc2UsCiAgICAicG9saWN5Q2hlY2siOiBmYWxzZSwKICAgICJzYm9tIjogZmFsc2UsCiAgICAiYWxsb3dlZENvbW1pdFNpZ25lcnMiOiBbCiAgICAgICJjcm9zc2ZhZGVyQGdtYWlsLmNvbSIsCiAgICAgICI3MjY4MzM3K2pmaWxsbWFuQHVzZXJzLm5vcmVwbHkuZ2l0aHViLmNvbSIKICAgIF0KICB9LAogICJzZWNyZXRzIjogWwogICAgewogICAgICAibmFtZSI6ICJzbGFjay13ZWJob29rLXVybCIKICAgIH0KICBdLAogICJub3RpZmljYXRpb25zIjogewogICAgInNsYWNrIjogewogICAgICAiZW5hYmxlZCI6IHRydWUsCiAgICAgICJjaGFubmVsIjogIiNhbGwtaWRwLWxhYiIKICAgIH0KICB9LAogICJkZXBsb3kiOiB7CiAgICAibG93ZXJFbnZpcm9ubWVudHMiOiBbCiAgICAgICJkZXYiCiAgICBdLAogICAgInVwcGVyRW52aXJvbm1lbnRzIjogWwogICAgICB7CiAgICAgICAgIm5hbWUiOiAicHJvZCIsCiAgICAgICAgImNsdXN0ZXIiOiAia2luZC1wcm9kIgogICAgICB9CiAgICBdCiAgfSwKICAicGlwZWxpbmVzIjogewogICAgImNpIjogewogICAgICAidHJpZ2dlciI6IHsKICAgICAgICAic291cmNlIjogImdpdCIsCiAgICAgICAgImV2ZW50IjogInB1c2giLAogICAgICAgICJicmFuY2giOiAibWFpbiIKICAgICAgfSwKICAgICAgInN0ZXBzIjogWwogICAgICAgIHsKICAgICAgICAgICJzdGFnZSI6ICJidWlsZCIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJzdGFnZSI6ICJkZXBsb3kiLAogICAgICAgICAgImVudiI6ICJkZXYiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAic3RhZ2UiOiAicmVsZWFzZSIsCiAgICAgICAgICAiZW52IjogInByb2QiCiAgICAgICAgfQogICAgICBdCiAgICB9CiAgfQp9Cg==
  relayHostAliasIP: 192.168.64.2
