appName: order-api
appType: app
cluster: kind-prod
envName: prod
rollout:
  image:
    repository: ghcr.io/jfillman/order-api
    tag: 0.1.2-13f78ae
  ports:
    - name: http
      containerPort: 8080
