appName: order-api
appType: app
cluster: kind-prod
envName: pre-prod
rollout:
  image:
    repository: ghcr.io/jfillman/order-api
    tag: 0.1.4-099cc19
  ports:
    - name: http
      containerPort: 8080
  livenessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 40
    timeoutSeconds: 30
  readinessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 40
    timeoutSeconds: 30
releaseTracking:
  cluster: kind-prod
  appNamespace: app-order-api-cicd
  gitUrl: https://github.com/jfillman/order-api
  gitRevision: 099cc191e341614db9ee899bdb4e74aa488fa913
  relayUrl: http://dev.kiac.local:30880/outcome/kind-prod
  flowStartTime: 2026-09-15T21:31:09.525Z
  chainId: bc03a78b-3ea1-4aab-a629-2fd3f83f9147
  configJsonB64: eyJhcGlWZXJzaW9uIjoicGxhdGZvcm0vdjEiLCJraW5kIjoiUGlwZWxpbmVDb25maWciLCJidWlsZCI6eyJhZ2VudCI6Im9wZW5qZGstMjEiLCJkb2NrZXJmaWxlIjoiLi9Eb2NrZXJmaWxlIiwidW5pdFRlc3QiOnsiZW5hYmxlZCI6ZmFsc2V9LCJjYWNoZSI6eyJlbmFibGVkIjp0cnVlLCJzaXplIjoic21hbGwifX0sImVwaGVtZXJhbEVudmlyb25tZW50cyI6eyJwdWxsUmVxdWVzdCI6eyJlbmFibGVkIjp0cnVlfSwidHRsIjoiNWQifSwiZ292ZXJuYW5jZSI6eyJzYXN0Ijp0cnVlLCJpbWFnZVNjYW4iOnRydWUsInBvbGljeUNoZWNrIjp0cnVlLCJzYm9tIjp0cnVlLCJhbGxvd2VkQ29tbWl0U2lnbmVycyI6WyJjcm9zc2ZhZGVyQGdtYWlsLmNvbSIsIjcyNjgzMzcramZpbGxtYW5AdXNlcnMubm9yZXBseS5naXRodWIuY29tIl19LCJzZWNyZXRzIjpbeyJuYW1lIjoic2xhY2std2ViaG9vay11cmwifV0sIm5vdGlmaWNhdGlvbnMiOnsic2xhY2siOnsiZW5hYmxlZCI6dHJ1ZSwiY2hhbm5lbCI6IiNhbGwtaWRwLWxhYiJ9LCJiYWNrc3RhZ2UiOnsiZW5hYmxlZCI6dHJ1ZX19LCJkZXBsb3kiOnsibG93ZXJFbnZpcm9ubWVudHMiOlsiZGV2IiwidGVzdCJdLCJ1cHBlckVudmlyb25tZW50cyI6W3sibmFtZSI6InByb2QiLCJjbHVzdGVyIjoia2luZC1wcm9kIn1dLCJwcm9tb3Rpb25PcmRlciI6WyJkZXYiLCJ0ZXN0IiwicHJvZCJdfSwicGlwZWxpbmVzIjp7ImNpIjp7InRyaWdnZXIiOnsic291cmNlIjoiZ2l0IiwiZXZlbnQiOiJwdXNoIiwiYnJhbmNoIjoibWFpbiJ9LCJzdGVwcyI6W3sic3RhZ2UiOiJidWlsZCJ9XX19fQ==
  relayHostAliasIP: "192.168.64.7"
